#!/bin/bash
DOCKER_TAG=regv2/$(whoami)/${GL_REPO}:latest

function prep_worktree() {
  GIT_DIR="$(pwd)"
  WORK_TREE="$(realpath "${GIT_DIR}/../../worktrees/")/${GL_REPO}"
  mkdir -p $WORK_TREE &&
  sudo git --work-tree=$WORK_TREE checkout -f main &&
  pushd $WORK_TREE &&
  sudo git --work-tree="$WORK_TREE" --git-dir="$GIT_DIR" submodule update --init --recursive
}

while read oldrev newrev ref; do
  if [[ $ref =~ .*/main$ ]]; then
    prep_worktree || exit 1

    [ "$(git ls-tree --full-tree -r main .worktreeonly)" != "" ] && exit

    if [ "$(git ls-tree --full-tree -r main Makefile)" != "" ]; then
      prep_worktree && make || exit 1
    elif [ "$(git ls-tree --full-tree -r main Dockerfile)" != "" ]; then
      docker build --pull -t $DOCKER_TAG . &&
      docker push $DOCKER_TAG || exit 1
    elif [ "$(git ls-tree --full-tree -r main docker-compose.yml)" != "" ]; then
      docker compose up -d --build --remove-orphans || exit 1
    fi
  fi
done
