#!/bin/bash -
#===============================================================================
#
#          FILE: gitolite-ssh
#
#         USAGE: gitolite-ssh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Mina Nagy Zaki (mnzaki), mnzaki@gmail.com
#  ORGANIZATION: mnzaki.com
#       CREATED: 01.12.2022 19:43:12
#      REVISION:  ---
#===============================================================================

set -o nounset                                  # Treat unset variables as an error

export GIT_DIR="$HOME/repository/$1"
export GIT_WORK_TREE="$HOME/worktrees/$1"
cd "$GIT_WORK_TREE" || exit 1
shift
echo -e \"git is bound\\nGIT_DIR=\$GIT_DIR\\nGIT_WORK_TREE=\$GIT_WORK_TREE\"
${@:-bash}
