#!/bin/bash -
#===============================================================================
#
#          FILE: gitolite-deploy.sh
#
#         USAGE: gitolite-deploy.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Mina Nagy Zaki (mnzaki), mnzaki@gmail.com
#  ORGANIZATION: mnzaki.com
#       CREATED: 01.12.2022 19:43:12
#      REVISION:  ---
#===============================================================================

set -o nounset                                  # Treat unset variables as an error

REPO="$HOME/worktrees/$1"
shift
cd "$REPO" &&
exec docker-compose $@
